Add support for Standard Chartered SG
bank2ynab/bank2ynab pull request #459
Opened 2024-04-20 17:32 UTC by limdingwen

**New Pull Request**

**Reference Issue:** #458
*Type # followed by the issue number this pull request pertains to*

**Description**
Add support for Standard Chartered SG. As part of this, adds XLS to CSV conversion support.

**Point of discussion:** SG SC has "Running Balance" as part of its export, which could be useful for YNABers reconciling. However, I left it out because I think it might be too confusing (inconsistent with other banks).

Note that trying to set a primarily number or price column to Memo or Payee results in an error in `dataframe_handler.clean_strings`.

It may be fixed by: `    modified_string_series = string_series.astype("string")`, but this was not included in this PR as it was not needed.

**Explain the changes that this pull request makes**
*Note that any submitted code must conform to the standards set by the Black linter. Please review the automated Linting test results on the pull request after saving and make any required changes or the submitted code will not be accepted.*

2024-04-20 17:33 UTC, limdingwen commented
Closes #458

2024-04-21 14:05 UTC, nocalla requested changes
This is great, thanks for doing the XLS plugin. I've reviewed the code and made a few suggestions - please take a look when you get a moment. 

Regarding your comments:

- Running balance isn't supported on import by YNAB unfortunately, so it's one that has to get dropped
- Your point about numerical Memo fields is an interesting one, you're probably correct in how it could be fixed, but we haven't had any reports of errors on this front to date.

2024-04-21 14:05 UTC, nocalla commented on bank2ynab.conf
> +Source CSV Delimiter = ,
You can omit entries that are the same as the default values to simplify the config, e.g. `Source CSV Delimiter = ,`. Check the defaults at the top of the file.

2024-04-25 16:08 UTC, limdingwen commented
Thanks! I've updated the code and pushed an amended version. Note that the bank's name has been corrected.

2024-04-28 13:37 UTC, nocalla approved these changes

2024-04-28 13:39 UTC, nocalla commented
Great, thanks for updating!

2024-04-28 13:39 UTC, merged